// <auto-generated />
namespace GymRS_DB_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class M02_DateError : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M02_DateError));
        
        string IMigrationMetadata.Id
        {
            get { return "202208042103382_M02_DateError"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
